Update meson build
nowsecure/frida-cycript pull request #38
Opened 2022-04-01 22:04 UTC by duraki

Following newest Meson trend, therefore this PR. Updates meson.build script to relative path of cycript0.9.

Test case:

```
$ rm -rf build && meson build --buildtype minsize --strip && ninja -C build
$ ./build/src/cycript
fcy#
```

Prior to this PR, following error was showing up: 

```
Compiler for C++ supports arguments -Wno-overloaded-virtual: YES
src/meson.build:168:2: ERROR: File cycript0.9 does not exist.
```

2022-04-01 23:39 UTC, oleavr requested changes
Thanks! Just one issue we need to figure out:

2022-04-01 23:39 UTC, oleavr commented on src/meson.build
> +      '../src/cycript0.9',
This assumes the build directory is at the root of the repo.

2022-04-03 03:37 UTC, eli-schwartz commented
input already guarantees that it is correctly relativized. The problem seems to be that `cycript0.9` is a directory, not a file, so Meson cannot really treat it as an input file (and in fact cannot find a file there at all). This means that using `files()` won't work either.

What you can do is `join_paths(meson.current_source_dir(), 'cycript0.9')`. Although I am actually not sure what it does at all -- apparently just copies this entire directory to the builddir as is?

You may also want to teach your script to output a depfile suitable for use as the `depfile: ...` kwarg to custom_target, this should be a file similar to the one gcc emits with the -M family of options: https://ninja-build.org/manual.html#_depfile

2022-04-05 23:36 UTC, duraki commented
Now uses `join_paths` as proposed by @eli-schwartz. It builds successfully as well.

2022-12-06 08:11 UTC, merged